### PR TITLE
Amj/dac client classes

### PR DESCRIPTION
**Pull request by jayich**
@aransfor , please take a look at this if you get a chance.  It is still in development but is largely working.  I'm trying to increase readability in addition to adding z squeezing and squeeze readouts.  I think it is mostly done, except for retroactively changing the old control logic.

### CODE REVIEW

**Comment by aransfor** [comment]
@jayich  ugh, massive duplication of effort.... I should have let you know I was working on this... essentially ground up so do as you will for now. too bad..

**Comment by jayich** [comment]
no worries, if you're working on lab stuff just move it on cards on Trello.  I'll notice it.

**Comment by jayich** [comment]
@aransfor , the changes here all seem to work.

**Comment by jayich** [comment]
@aransfor , please take a look.  I have moved the electrode classes out of the dacclient.py module.  My next step is to start merging in the GUI control that you have made.

**Comment by aransfor** [comment]
@jayich LGTM, I would merge asap as I predict there is still a couple weeks before the new dac client is ready for primetime

**Pull request merged**
